# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lab5' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lab5

  target 'lab5Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'lab5UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
